package com.bestbuy.sdp.ejb;


/*
  ** This file was automatically generated by 
  ** EJBGen WebLogic Server 10.3.3.0  Fri Apr 9 00:05:28 PDT 2010 1321401 
*/


import javax.ejb.EJBObject;
import java.rmi.RemoteException;

// BEGIN imports from bean class
import javax.ejb.SessionBean;
import weblogic.ejb.GenericSessionBean;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.LocalMethod;
import weblogic.ejbgen.RemoteMethod;
import weblogic.ejbgen.Session;
// END imports from bean class


/**
 * * 
 * GenericSessionBean subclass automatically generated by OEPE.
 * Please complete the ejbCreate method as needed to properly initialize new instances of your bean and add
 * all required business methods. Also, review the Session, JndiName and FileGeneration annotations 
 * to ensure the settings match the bean's intended use.
 
 */

public interface HelloWorldRemote extends EJBObject {


  /**
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public String sayHello(String name)     throws RemoteException;

}
