package com.bestbuy.sdp.ejb;


/*
  ** This file was automatically generated by 
  ** EJBGen WebLogic Server 10.3.3.0  Fri Apr 9 00:05:28 PDT 2010 1321401 
*/


import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import javax.ejb.FinderException;
import java.rmi.RemoteException;
import java.util.Collection;

// BEGIN imports from bean class
import com.accenture.common.ex.ApplicationException;
import com.accenture.xml.sdp.bby.om.bbyOrder.BBYOrder;
import com.accenture.xml.sdp.bby.om.bbyOrder.BBYOrderDocument;
import com.accenture.xml.sdp.bby.serviceResult.ServiceResult;
import com.accenture.xml.sdp.bby.serviceResult.ServiceResultDocument;
import com.bestbuy.schemas.sdp.db.createOrder.CreateOrderRequestDocument;
import com.bestbuy.schemas.sdp.db.createOrder.CreateOrderResponseDocument;
import com.bestbuy.schemas.sdp.db.insertException.InsertExceptionRequestDocument;
import com.bestbuy.schemas.sdp.db.retrieveCatalog.RetrieveCatalogOfferRequestDocument;
import com.bestbuy.schemas.sdp.db.retrieveCatalog.RetrieveCatalogOfferResponseDocument;
import com.bestbuy.schemas.sdp.db.retrieveOrder.RetrieveOrderRequestDocument;
import com.bestbuy.schemas.sdp.db.retrieveOrder.RetrieveOrderResponseDocument;
import com.bestbuy.schemas.sdp.db.updateOrder.UpdateOrderRequestDocument;
import com.bestbuy.schemas.sdp.db.updateOrder.UpdateOrderResponseDocument;
import com.bestbuy.sdp.catalog.SDPCatalogDB;
import com.bestbuy.sdp.order.SDPOrderDB;
import com.bestbuy.sdp.services.exception.SDPInternalException;
import java.sql.SQLException;
import javax.ejb.SessionBean;
import org.apache.xmlbeans.XmlException;
import org.apache.xmlbeans.XmlObject;
import weblogic.ejb.GenericSessionBean;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.LocalMethod;
import weblogic.ejbgen.RemoteMethod;
import weblogic.ejbgen.Session;
// END imports from bean class


/**
 * * 
 * GenericSessionBean subclass automatically generated by OEPE.
 * Please complete the ejbCreate method as needed to properly initialize new instances of your bean and add
 * all required business methods. Also, review the Session, JndiName and FileGeneration annotations 
 * to ensure the settings match the bean's intended use.
 
 */

public interface SdpDBServiceRemoteHome extends EJBHome {



  public SdpDBServiceRemote create()     throws CreateException, RemoteException, javax.ejb.CreateException;



}
