package com.bestbuy.sdp.ejb;


/*
  ** This file was automatically generated by 
  ** EJBGen WebLogic Server 10.3.3.0  Fri Apr 9 00:05:28 PDT 2010 1321401 
*/


import javax.ejb.EJBObject;
import java.rmi.RemoteException;

// BEGIN imports from bean class
import com.accenture.common.ex.ApplicationException;
import com.accenture.xml.sdp.bby.om.bbyOrder.BBYOrder;
import com.accenture.xml.sdp.bby.om.bbyOrder.BBYOrderDocument;
import com.accenture.xml.sdp.bby.serviceResult.ServiceResult;
import com.accenture.xml.sdp.bby.serviceResult.ServiceResultDocument;
import com.bestbuy.schemas.sdp.db.createOrder.CreateOrderRequestDocument;
import com.bestbuy.schemas.sdp.db.createOrder.CreateOrderResponseDocument;
import com.bestbuy.schemas.sdp.db.insertException.InsertExceptionRequestDocument;
import com.bestbuy.schemas.sdp.db.retrieveCatalog.RetrieveCatalogOfferRequestDocument;
import com.bestbuy.schemas.sdp.db.retrieveCatalog.RetrieveCatalogOfferResponseDocument;
import com.bestbuy.schemas.sdp.db.retrieveOrder.RetrieveOrderRequestDocument;
import com.bestbuy.schemas.sdp.db.retrieveOrder.RetrieveOrderResponseDocument;
import com.bestbuy.schemas.sdp.db.updateOrder.UpdateOrderRequestDocument;
import com.bestbuy.schemas.sdp.db.updateOrder.UpdateOrderResponseDocument;
import com.bestbuy.sdp.catalog.SDPCatalogDB;
import com.bestbuy.sdp.order.SDPOrderDB;
import com.bestbuy.sdp.services.exception.SDPInternalException;
import java.sql.SQLException;
import javax.ejb.SessionBean;
import org.apache.xmlbeans.XmlException;
import org.apache.xmlbeans.XmlObject;
import weblogic.ejb.GenericSessionBean;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.LocalMethod;
import weblogic.ejbgen.RemoteMethod;
import weblogic.ejbgen.Session;
// END imports from bean class


/**
 * * 
 * GenericSessionBean subclass automatically generated by OEPE.
 * Please complete the ejbCreate method as needed to properly initialize new instances of your bean and add
 * all required business methods. Also, review the Session, JndiName and FileGeneration annotations 
 * to ensure the settings match the bean's intended use.
 
 */

public interface SdpDBServiceRemote extends EJBObject {


  /**
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public void createCommsatLog(String subscriptionOfferId, String emailId, String redemptionCode, String templateId, String status, String userId, String confirmationId, String transactionDate, String bbyId, String lineItemId, String regId)     throws RemoteException;

  /**
   * * 
 * Java callout method. Extract information from xml to insert information
 * SDP_EXCEPTION_MESSAGE_LOG table returns generated response this method is
 * called when request is in xml form other then BBYOrder.
 * throws ApplicationException
 * @param requestXmlObject
 * @throws ApplicationException
 
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public void createExceptionMessage(org.apache.xmlbeans.XmlObject requestXmlObject, String sdpId, String sdpOrderId, String srcSysId)     throws RemoteException, com.accenture.common.ex.ApplicationException;

  /**
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public void createMerchantLinkTokenLog(String subscriptionOfferId, String vendorID, String bBYID, String custName, String ccToken, String cardType, String expirationDate, String address1, String address2, String city, String state, String zip, String processedFlag)     throws RemoteException;

  /**
   * * 
 * This is a Java callout method which accepts XML as a parameter to create
 * new order, it also generates response for that request. Returns that
 * response in xml form. This method is called when request is in xml form
 * other then BBYOrder.
 * throws ApplicationException
 * @param requestXmlObject
 * @return xmlResponseDoc
 * @throws ApplicationException
 
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public com.bestbuy.schemas.sdp.db.createOrder.CreateOrderResponseDocument createOrder(org.apache.xmlbeans.XmlObject requestXmlObject)     throws RemoteException, com.accenture.common.ex.ApplicationException;

  /**
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public String getTemplateId(String sku, String dateString)     throws RemoteException;

  /**
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public com.bestbuy.schemas.sdp.db.retrieveCatalog.RetrieveCatalogOfferResponseDocument retrieveCatalogByDigitalAttributes(org.apache.xmlbeans.XmlObject requestXmlObject)     throws RemoteException, com.accenture.common.ex.ApplicationException;

  /**
   * * 
 * Java callout method. Retrieves catalog information by sku and generate
 * appropriate response for the order returns response
 * throws ApplicationException
 * @param requestXmlObject
 * @return xmlResponseDoc
 * @throws ApplicationException
 
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public com.bestbuy.schemas.sdp.db.retrieveCatalog.RetrieveCatalogOfferResponseDocument retrieveCatalogBySku(org.apache.xmlbeans.XmlObject requestXmlObject)     throws RemoteException, com.accenture.common.ex.ApplicationException;

  /**
   * * 
 * Java callout method. Retrieves order information and generate appropriate
 * response for the order returns response
 * throws ApplicationException
 * @param requestXmlObject
 * @return xmlResponseDoc
 * @throws ApplicationException
 
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public com.bestbuy.schemas.sdp.db.retrieveOrder.RetrieveOrderResponseDocument retrieveOrder(org.apache.xmlbeans.XmlObject requestXmlObject)     throws RemoteException, com.accenture.common.ex.ApplicationException;

  /**
   * * 
 * Java callout method. Updates information of the order returns
 * xmlResponseDoc, appropriate response for the order. This method is called
 * when request is in xml form other then BBYOrder.
 * throws ApplicationException
 * @param requestXmlObject
 * @return xmlResponseDoc
 * @throws ApplicationException
 
   * @weblogic.ejbgen.LocalMethod 
   * @weblogic.ejbgen.RemoteMethod 
   */
  public com.bestbuy.schemas.sdp.db.updateOrder.UpdateOrderResponseDocument updateOrder(org.apache.xmlbeans.XmlObject requestXmlObject)     throws RemoteException, com.accenture.common.ex.ApplicationException;

}
