package com.bestbuy.sdp.ejb;

import javax.ejb.SessionBean;

import weblogic.ejb.GenericSessionBean;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.LocalMethod;
import weblogic.ejbgen.RemoteMethod;
import weblogic.ejbgen.Session;

/**
 * GenericSessionBean subclass automatically generated by OEPE.
 *
 * Please complete the ejbCreate method as needed to properly initialize new instances of your bean and add
 * all required business methods. Also, review the Session, JndiName and FileGeneration annotations 
 * to ensure the settings match the bean's intended use.
 */
@Session(ejbName = "HelloWorld")
@JndiName(remote = "ejb.HelloWorldRemoteHome", local = "ejb.HelloWorldLocalHome")
@FileGeneration(remoteClass = Constants.Bool.TRUE, remoteHome = Constants.Bool.TRUE, 
		localClass = Constants.Bool.TRUE, localHome = Constants.Bool.TRUE)
public class HelloWorld extends GenericSessionBean implements SessionBean {
	private static final long serialVersionUID = 1L;

	/* (non-Javadoc)
	 * @see weblogic.ejb.GenericSessionBean#ejbCreate()
	 */
	public void ejbCreate() {
		// IMPORTANT: Add your code here
	}

	// IMPORTANT: Add business methods
	@RemoteMethod
	@LocalMethod
	public String sayHello(String name){
		return "Hello " + name;
	}
}